config/routes.rb
Rails.application.routes.draw do
  get 'sidebar/index'

  root to: 'visitors#index'
  devise_for :users,controllers: {:registrations => "registrations"}
  resources :users
	as :user do
	  get "/register", to: "registrations#new", as: "register"
	  get "/maps/moremaps", to: "maps#moremaps"
	end
	resources :maps do
		collection {post:import}
		collection {post:ctg}
	end
	as :map do		
		get "maps/:id/vgs", to:"maps#vgs" , as: "groupsummary"		
		get "maps/:id/vcm", to:"maps#vcm" , as: "correlationmatrix"		
		get "maps/:id/vsg", to:"maps#viewsinglegraph" , as: "singlegraph"
		get "maps/:id/md", to:"maps#mapdashboard" , as: "mapdashboard"
	end	
end

app/models/map.rb
class Map < ApplicationRecord	
	require 'csv'	
	enum status: [:published, :unpublished]
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def new		
	end
  def show
  	$selectedmap = Map.find(params[:id])
  	@map = Map.find(params[:id])					

	unless @map.sourcefile.nil?
		open_file_name = Rails.root.join('public', 'uploads', @map.sourcefile)
		if File.exist?(open_file_name)
			@csv_table = CSV.open(open_file_name, :headers => true).read	
		else
			@map.update(sourcefile: nil)
			redirect_to @map, :notice => "Sorry but we couldn't open that file. Please upload file again"
		end		
	end
  end
  def index
  	@maps = Map.all
  end

  def edit
  	@map = Map.find(params[:id])
  end
  
  def update
		@map = Map.find(params[:id])

		if @map.update(map_params)
		  redirect_to @map
		else
		  render 'edit'
		end
	end
	
	def create
	  @map = Map.new(map_params)
	 
	  if @map.save
	    redirect_to @map
	  else
	    render 'new'
	  end
	end

	def vcm		
		set_csv
	end

	def vgs
		set_csv
	end
	def moremaps
		@map = Map.all
	end

	def import		
		uploaded_io = params[:sourcefile]
		
		if uploaded_io.nil?

		else
			uploaded_file_name = Time.now.strftime("%d%m%y%H%M%S").to_s + uploaded_io.original_filename.to_s
			
			File.open(Rails.root.join('public', 'uploads', uploaded_file_name), 'wb') do |file|
			  file.write(uploaded_io.read)
			end					
			
			headers = CSV.read(Rails.root.join('public', 'uploads', uploaded_file_name), headers: true).headers
			headers.shift(4)	
			
			#Save traits
			trait = Trait.new(trait: headers)
			trait.save
			
			#Save tags			
			@csv_table = CSV.open(Rails.root.join('public', 'uploads', uploaded_file_name), :headers => true).read
			tags_array = Array.new			
			
			@csv_table.each do |row1|
				tmp_str = row1[3].to_s.downcase.gsub! ', ', ','				
				tmp_row1 = tmp_str.split(',')
				tags_array = tags_array | tmp_row1
			end				

			tag = Tag.new(tag: tags_array.to_s)
			tag.save

			@map = Map.find(params[:id])	
			if @map.update(sourcefile: uploaded_file_name,trait_id: trait.id, tags_id: tag.id)
			  redirect_to @map		
			end
		end
	end

	def ctg
		selected_traits = params[:selected_traits]		
		traitgroup = Traitgroup.new(traitgroup: selected_traits, trait_group_name: params[:trait_group_name])
		traitgroup.save
		@map = Map.find(params[:id])		
		if @map.traitgroups_id.nil?
			if @map.update(traitgroups_id: traitgroup.id)		
		  	redirect_to @map		
			end
		else 
			ts = @map.traitgroups_id.to_s + ',' + traitgroup.id.to_s
			if @map.update(traitgroups_id: ts)		
		  	redirect_to @map		
			end
		end
	end

	def viewsinglegraph
		set_csv
	end

	def mapdashboard
		set_csv		
	end
	private
	def map_params
		params.require(:map).permit(:datapoints, :maptitle)
	end	  
	# Statistics calculation methods
  	def stats_average(data)
    	total = data.inject(:+)
    	len = data.length
    	average = data.to_f / len 
  	end
  	def stats_mode(data)
    	data = [1, 1, 1, 2, 3]
    	freq = data.inject(Hash.new(0)) { |h,v| h[v] += 1; h }
    	data.max_by { |v| freq[v] }
  	end

  	def sum
    	self.inject(0){|accum, i| accum + i }
  	end

	def mean
    	self.sum/self.length.to_f
  	end

  	def sample_variance
    	m = self.mean
    	sum = self.inject(0){|accum, i| accum +(i-m)**2 }
    	sum/(self.length - 1).to_f
  	end

  	def standard_deviation
    	return Math.sqrt(self.sample_variance)
  	end
  
  	def percentile(values, percentile)
    	values_sorted = values.sort
    	k = (percentile*(values_sorted.length-1)+1).floor - 1
    	f = (percentile*(values_sorted.length-1)+1).modulo(1)
		return values_sorted[k] + (f * (values_sorted[k+1] - values_sorted[k]))
	end
	def count_min_to_max(arr,min,max)
		cnt = 0
  		arr.each do |element|  		
  			if ( element.to_f >= min.to_f && element.to_f <=max.to_f)
				  cnt +=1
				end		
  		end  	
		cnt
 	end
 	def calc_cor(x,y,n)
 		deno = sqrt(x**2 - (x**2)/n) * sqrt(y**2 - (y**2)/n)
 		nume = x*y - x*y/n
 		nume / deno
 	end 	

 	def set_csv
		@map = Map.find(params[:id])	

		@trait = Trait.find(@map.trait_id)
		unless @map.traitgroups_id.nil?
			group_ids = @map.traitgroups_id.split(',')

			@traitgroups = Traitgroup.find(group_ids)		
			@group_array = Array.new
			@traitgroups.each do |group|
				@group_array.push(group.trait_group_name)
			end
		end

		
		unless @map.tags_id.nil?
			tags_id = @map.tags_id

			@tags = Tag.find(tags_id)		
			@tags = @tags.tag.to_s
		end

		unless @map.sourcefile.nil?
			open_file_name = Rails.root.join('public', 'uploads', @map.sourcefile)
			@csv_table = CSV.open(open_file_name, :headers => true).read	
			
			@csv_header = CSV.read(Rails.root.join('public', 'uploads', open_file_name), headers: true).headers			
			@csv_header.shift(4)	
			@csv_body = Array.new
			tmp_row   = Array.new
			vgs_row   = Array.new

			#Statistics Array
			min_row    = Array.new
			max_row    = Array.new
			range_row  = Array.new
			mean_row   = Array.new
			median_row = Array.new
			count80_row = Array.new
			count20_row = Array.new
			count40_row = Array.new
			count60_row = Array.new
			count100_row = Array.new

			min_row.push('Minimum Score')
			max_row.push('Maximum Score')			
			count20_row.push('Count 0-20')
			count40_row.push('Count 21-40')
			count60_row.push('Count 41-60')
			count80_row.push('Count 61-80')
			count100_row.push('Count 81-100')
			@csv_header.each_with_index do |row, i| 
				vgs_row = []
				tmp_row = []
				@csv_table.each do |row1|
					tmp_row.push(row1[i+4])
				end								
				min_row.push(tmp_row.min)				
				max_row.push(tmp_row.max)
				count20_row.push(count_min_to_max(tmp_row,0,20))				
				count40_row.push(count_min_to_max(tmp_row,21,40))
				count60_row.push(count_min_to_max(tmp_row,41,60))
				count80_row.push(count_min_to_max(tmp_row,61,80))
				count100_row.push(count_min_to_max(tmp_row,81,100))
			end			
			@csv_body.push(min_row)
			@csv_body.push(max_row)			
			@csv_body.push(count20_row)			
			@csv_body.push(count40_row)
			@csv_body.push(count60_row)
			@csv_body.push(count80_row)
			@csv_body.push(count100_row)
			@csv_header.unshift('Statistical Data Point')
		end
 	end
end

  	
  

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_detaillink.html.erb
<li class="span_li"><span> <%= $selectedmap.maptitle %></span>
<span> (N=<%= $selectedmap.datapoints %>, Last Edited <%= $selectedmap.updated_at %>) </span></li>
<li><%= link_to "View Source Data", map_path($selectedmap) ,:class => 'menu-item detail-menu'%></li>
<li><%= link_to "View Group Summary", groupsummary_path($selectedmap) ,:class => 'menu-item detail-menu'%></li>
<li><%= link_to "View Correlation Matrix", correlationmatrix_path($selectedmap) ,:class => 'menu-item detail-menu'%></li>
<li><%= link_to "View Single Graph", singlegraph_path($selectedmap) ,:class => 'menu-item detail-menu'%></li>
<li><%= link_to "Map Dashboard", mapdashboard_path($selectedmap) ,:class => 'menu-item detail-menu'%></li>

app/views/maps/_map.html.erb
<td>
	<%= map.maptitle.titleize unless map.maptitle.nil?%>
</td>
<td>
  <%= 'N = ' + map.datapoints.to_s %>
</td>
<td>
	<%= map.created_at %>
</td>
<td>
	<%= map.updated_at %>
</td>
<td>
	<%= link_to "Update Map", edit_map_path(map)%>
</td>

app/views/maps/_mapside.html.erb
<ul>
  <% @maps.each do |map| %>
  <li>
      <a href="#" class="menu-item">
          <%= map.maptitle %>
      </a>
  </li>
  <% end %>
</ul>

app/views/maps/_moremapshead.erb
<th> Map Title </th>
<th> Data Points </th>
<th> Created </th>
<th> Updated</th>
<th> Edit </th>

app/views/maps/edit.html.erb
<div class="register-form">
  
<%= form_for :map, url: maps_path do |f| %>
    <div class="form-header">
    <span>Add / Manage Map</span>
    </div>
    <div class="form-body">      
      <div class="form-group">
        <%= f.label :maptitle, 'Map title' %>
        <%= f.text_field :maptitle, :autofocus => true, class: 'form-control' %>
      </div>      
      <div class="form-group">
        <%= f.label :datapoints, 'Data Points' %>
        <%= f.number_field :datapoints, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= link_to 'Cancel', maps_path, :class=>'btn outlined-btn' %> 
        <%= f.submit 'Save', :class => 'button right', :id=>'save_btn'%>      
      </div>
    </div>
  <% end %>
</div>

app/views/maps/index.html.erb
<h1>Listing maps</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @maps.each do |map| %>
    <tr>
      <td><%= map.maptitle %></td>
      <td><%= map.datapoints %></td>
      <td><%= link_to 'Show', map_path(map) %></td>
    </tr>
  <% end %>
</table>

app/views/maps/mapdashboard.html.erb
<%= stylesheet_link_tag 'map_dashboard' %>
<div class='row'>
<input type="hidden" class="page_type" value="map_dashboard"/>
<h4> Map Dashboard: <%= @map.maptitle %> </h4>
<span> Select Data for Map Group Data Summary </span>
<div class='pull-right'>
<button type="button" class="btn btn-primary"> Export Selection as Map </button>
<button type="button" class="btn btn-primary"> Export Entire Map </button>
</div>
</div>
<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">GROUPS</legend>
  Include Groups: <textarea id="inGroups" name='tags2' placeholder='Add Groups'></textarea><br>
  Exclude Groups: <textarea id="exGroups" name='tags2' placeholder='Add Groups'></textarea><br>  
 </fieldset>
</div>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TAGS</legend>
  Include Tags: <textarea id="inTags" name='tags2' placeholder='Add Tags'></textarea><br>
  Exclude Tags: <textarea id="exTags" name='tags2' placeholder='Add Tags'></textarea><br>  
 </fieldset>
</div>
</div>

<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TRAITS</legend>
  Include Traits: <textarea id="inTraits" name='tags2' placeholder='Add Traits'></textarea><br>
  Exclude Traits: <textarea id="exTraits" name='tags2' placeholder='Add Traits'></textarea><br>  
 </fieldset>
</div>

<div class='col-sm-6'>
 <fieldset>
  <legend align="center">STATISTICS</legend>
  Include Traits: <textarea id="inStats" name='tags2' placeholder='Add Statistics'></textarea><br>
  Exclude Traits: <textarea id="exStats" name='tags2' placeholder='Add Statistics'></textarea><br>  
 </fieldset>
</div>
</div>
<input id="traitValues" value='<%= @trait.trait %>' type="hidden" /> 
<input id="traitgroupValues" value='<%= @group_array %>' type="hidden" /> 
<input id="tagsValues" value='<%= @tags %>' type="hidden" /> 

<%= hidden_field_tag :id, @map.id%>
<%= hidden_field_tag :selected_traits, @map.id%>
<div class='chart_wrapper col-sm-8 col-sm-offset-2 text-center'>
  <div id="box_plots">

  </div>
</div>
<div class='chart_wrapper col-sm-8 col-sm-offset-2 text-center'>
<div id="mean_standard_deviation">
</div>
</div>
<div class='chart_wrapper col-sm-8 col-sm-offset-2 text-center'>
<div id="radar_chart">

</div>
</div>
<div class='chart_wrapper col-sm-8 col-sm-offset-2 text-center'>
<div id="group_heat_map">

</div>
</div>
<%= javascript_include_tag('box_plots.js') %>

app/views/maps/moremaps.html.erb
<h3>Maps</h3>     
<table id="more_maps_table" class="table responsive no-wrap">
  <thead>
    <%= render 'moremapshead' %>
  </thead>
  <tbody>
    <% @map.each do |map| %>
      <tr>
        <%= render map %>
      </tr>
    <% end %>
  </tbody>
</table>          

app/views/maps/new.html.erb
<div class="register-form">
  
<%= form_for :map, url: maps_path do |f| %>
    <div class="form-header">
    <span>Add / Manage Map</span>
    </div>
    <div class="form-body">      
      <div class="form-group">
        <%= f.label :maptitle, 'Map title' %>
        <%= f.text_field :maptitle, :autofocus => true, class: 'form-control' %>
      </div>      
      <div class="form-group">
        <%= f.label :datapoints, 'Data Points' %>
        <%= f.number_field :datapoints, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= link_to 'Cancel', maps_path, :class=>'btn outlined-btn' %> 
        <%= f.submit 'Save', :class => 'button right', :id=>'save_btn'%>      
      </div>
    </div>
  <% end %>
</div>

app/views/maps/show.html.erb
<div class="row">
<div class="col-sm-12">
<input type="hidden" class="page_type" value="view_source_data"/>
<h4> Source Data: <%= @map.maptitle %> </h4>
<h4> Add Data to Map</h4>
<%= form_tag import_maps_path, multipart: true do %>
	<%= file_field_tag :sourcefile %>
	<%= hidden_field_tag :id, @map.id%>
	<%= submit_tag "Upload" %>
<% end %>
<% unless @csv_table.nil? %>
<table id="vsd_table">
<thead>
  <tr>
  <% @csv_table.headers.each do |header| %>
    <th><%= header %></th>
  <% end %> 
  </tr>
  </thead>
  <tbody>
  <% @csv_table.each do |row| %>
    <tr>
    <% row.each do |element| %>
      <td><%= element[1] %></td>
    <% end %>
    </tr>
  <% end %> 
  </tbody>
</table>
<% end %>
</div>
</div>

app/views/maps/vcm.html.erb
<div class='row'>
<input type="hidden" class="page_type" value="view_correlation_matrix"/>
<h4> Population Correlation Matrix: <%= @map.maptitle %> </h4>
<span> Select Data for Map Group Data Summary </span>
<button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#ctgmodal"> Create Trait Group </button>
</div>
<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">GROUPS</legend>
  Include Groups: <textarea id="inGroups" name='tags2' placeholder='Add Groups'></textarea><br>
  Exclude Groups: <textarea id="exGroups" name='tags2' placeholder='Add Groups'></textarea><br>  
 </fieldset>
</div>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TAGS</legend>
  Include Tags: <textarea id="inTags" name='tags2' placeholder='Add Tags'></textarea><br>
  Exclude Tags: <textarea id="exTags" name='tags2' placeholder='Add Tags'></textarea><br>  
 </fieldset>
</div>
</div>

<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TRAITS</legend>
  Include Traits: <textarea id="inTraits" name='tags2' placeholder='Add Traits'></textarea><br>
  Exclude Traits: <textarea id="exTraits" name='tags2' placeholder='Add Traits'></textarea><br>  
 </fieldset>
</div>

<div class='col-sm-6'>
 <fieldset>
  <legend align="center">STATISTICS</legend>
  Include Traits: <textarea id="inStats" name='tags2' placeholder='Add Statistics'></textarea><br>
  Exclude Traits: <textarea id="exStats" name='tags2' placeholder='Add Statistics'></textarea><br>  
 </fieldset>
</div>
</div>
<input id="traitValues" value='<%= @trait.trait %>' type="hidden" /> 
<input id="traitgroupValues" value='<%= @group_array %>' type="hidden" /> 
<input id="tagsValues" value='<%= @tags %>' type="hidden" /> 
<div class='chart_wrapper col-sm-8 col-sm-offset-2 text-center'>
<div id="matrix">
    <div style="display:inline-block;" id="legend"></div>
    <div style="display:inline-block; float:left" id="container"></div>
</div>
</div>

<!-- Modal -->
<div id="ctgmodal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <%= form_tag ctg_maps_path, :id => 'ctg_modal', multipart: true do %>
  
  <%= hidden_field_tag :id, @map.id%>
  <%= hidden_field_tag :selected_traits, @map.id%>  

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create/Manage Trait Group</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">          
          <div class="col-12">            
            Tag Group Name : <br/>
            <%= text_field_tag :trait_group_name, nil, placeholder:"Trait Group Name"%>
          </div>
          <div class="col-12">
          <br/>
          <p> Click to Select Traits to Include in Group </p>
          </div>
        </div>             
        <% csv_headers = @csv_table.headers
          csv_headers.shift(4)
        %>
        <div id="checkbox_wrapper">
        <% csv_headers.each do |button| %>
        <span class="button-checkbox">
          <button type="button" class="btn" data-color="default"><%= button %></button>
          <input type="checkbox" class="hidden" checked />
        </span>                       
        <% end %>   
        </div>
      </div>
      <div class="modal-footer">
        <%= submit_tag "Save", class: "btn btn-primary"%>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/maps/vgs.html.erb
<div class='row'>
<input type="hidden" class="page_type" value="view_group_summary"/>
<h4> Group Summary: <%= @map.maptitle %> </h4>
<span> Select Data for Map Group Data Summary </span>
<button type="button" class="btn btn-primary pull-right" data-toggle="modal" data-target="#ctgmodal"> Create Trait Group </button>
</div>
<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">GROUPS</legend>
  Include Groups: <textarea id="inGroups" name='tags2' placeholder='Add Groups'></textarea><br>
  Exclude Groups: <textarea id="exGroups" name='tags2' placeholder='Add Groups'></textarea><br>  
 </fieldset>
</div>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TAGS</legend>
  Include Tags: <textarea id="inTags" name='tags2' placeholder='Add Tags'></textarea><br>
  Exclude Tags: <textarea id="exTags" name='tags2' placeholder='Add Tags'></textarea><br>  
 </fieldset>
</div>
</div>

<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TRAITS</legend>
  Include Traits: <textarea id="inTraits" name='tags2' placeholder='Add Traits'></textarea><br>
  Exclude Traits: <textarea id="exTraits" name='tags2' placeholder='Add Traits'></textarea><br>  
 </fieldset>
</div>

<div class='col-sm-6'>
 <fieldset>
  <legend align="center">STATISTICS</legend>
  Include Traits: <textarea id="inStats" name='tags2' placeholder='Add Statistics'></textarea><br>
  Exclude Traits: <textarea id="exStats" name='tags2' placeholder='Add Statistics'></textarea><br>  
 </fieldset>
</div>
</div>
<h4> CSV Result </h4>

<input id="traitValues" value='<%= @trait.trait %>' type="hidden" /> 
<input id="traitgroupValues" value='<%= @group_array %>' type="hidden" /> 
<input id="tagsValues" value='<%= @tags %>' type="hidden" /> 

<% unless @csv_table.nil? %>
<table id="vgs_table">
<thead>
  <tr>
  <% @csv_header.each do |header| %>
    <th><%= header %></th>
  <% end %> 
  </tr>
  </thead>
  <tbody>
  <% @csv_body.each do |row| %>
    <tr>
    <% row.each do |element| %>
      <td><%= element %></td>
    <% end %>
    </tr>
  <% end %> 
  </tbody>
</table>
<% end %>

<!-- Modal -->
<div id="ctgmodal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <%= form_tag ctg_maps_path, :id => 'ctg_modal', multipart: true do %>
  
  <%= hidden_field_tag :id, @map.id%>
  <%= hidden_field_tag :selected_traits, @map.id%>

    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Create/Manage Trait Group</h4>
      </div>
      <div class="modal-body">
        <div class="form-group">          
          <div class="col-12">                        
            <%= text_field_tag :trait_group_name, nil, placeholder:"Trait Group Name"%>
          </div>
          <div class="col-12">
          <br/>
          <p> Click to Select Traits to Include in Group </p>
          </div>
        </div>             
        <% csv_headers = @csv_table.headers
          csv_headers.shift(4)
        %>
        <div id="checkbox_wrapper">
        <% csv_headers.each do |button| %>
        <span class="button-checkbox">
          <button type="button" class="btn" data-color="default"><%= button %></button>
          <input type="checkbox" class="hidden" checked />
        </span>                       
        <% end %>   
        </div>
      </div>
      <div class="modal-footer">
        <%= submit_tag "Save", class: "btn btn-primary"%>
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/maps/viewsinglegraph.html.erb
<div class='row'>
<input type="hidden" class="page_type" value="view_single_graph"/>
<h4> Single Graph: <%= @map.maptitle %> </h4>
<span> Select Data and Graph Type </span>
 <div class="dropdown pull-right">
  <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">Select Chart Type
  <span class="caret"></span></button>
  <ul class="dropdown-menu">
    <li><a href="#">Box Plot</a></li>
    <li><a href="#">Radar</a></li>
    <li><a href="#">Heatmap</a></li>
  </ul>
</div> 
<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">GROUPS</legend>
  Include Groups: <textarea id="inGroups" name='tags2' placeholder='Add Groups'></textarea><br>
  Exclude Groups: <textarea id="exGroups" name='tags2' placeholder='Add Groups'></textarea><br>  
 </fieldset>
</div>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TAGS</legend>
  Include Tags: <textarea id="inTags" name='tags2' placeholder='Add Tags'></textarea><br>
  Exclude Tags: <textarea id="exTags" name='tags2' placeholder='Add Tags'></textarea><br>  
 </fieldset>
</div>
</div>

<div class='row'>
<div class='col-sm-6'>
 <fieldset>
  <legend align="center">TRAITS</legend>
  Include Traits: <textarea id="inTraits" name='tags2' placeholder='Add Traits'></textarea><br>
  Exclude Traits: <textarea id="exTraits" name='tags2' placeholder='Add Traits'></textarea><br>  
 </fieldset>
</div>

<div class='col-sm-6'>
 <fieldset>
  <legend align="center">STATISTICS</legend>
  Include Traits: <textarea id="inStats" name='tags2' placeholder='Add Statistics'></textarea><br>
  Exclude Traits: <textarea id="exStats" name='tags2' placeholder='Add Statistics'></textarea><br>  
 </fieldset>
</div>
</div>
<input id="traitValues" value='<%= @trait.trait %>' type="hidden" /> 
<input id="traitgroupValues" value='<%= @group_array %>' type="hidden" /> 
<input id="tagsValues" value='<%= @tags %>' type="hidden" /> 

<%= hidden_field_tag :id, @map.id%>
<%= hidden_field_tag :selected_traits, @map.id%>

<br/>
<div class=row>
<div class='col-sm-12'>
<button type="button" class="btn btn-primary pull-right"> Export Chart </button>
<button type="button" class="btn btn-primary pull-left" disabled="disabled"> Create Comparison </button>
</div>
</div>