config/routes.rb
Rails.application.routes.draw do
  get 'sidebar/index'

  root to: 'visitors#index'
  devise_for :users,controllers: {:registrations => "registrations"}
  resources :users
	as :user do
	  get "/register", to: "registrations#new", as: "register"
	  get "/maps/moremaps", to: "maps#moremaps"
	end
	resources :maps do
		collection {post:import}
		collection {post:ctg}
	end
	as :map do		
		get "maps/:id/vgs", to:"maps#vgs" , as: "groupsummary"		
		get "maps/:id/vcm", to:"maps#vcm" , as: "correlationmatrix"		
		get "maps/:id/vsg", to:"maps#viewsinglegraph" , as: "singlegraph"
		get "maps/:id/md", to:"maps#mapdashboard" , as: "mapdashboard"
	end	
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :"map creator", :admin,:'map viewer']
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    $selectedmap = nil
    @users = User.all
  end

  def show
    $selectedmap = nil
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])        
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
  
  def edit
    $selectedmap = nil
     @user = User.find(params[:id])
   end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:contact, :phone, :caa,:cua,:pm,:etp,:vsd,:eci,:role)
  end
end

app/views/users/_user.html.erb
<td>
	<%= user.name.titleize unless user.name.nil?%>
</td>
<td>
  <%= link_to user.email, user %>
</td>
<td>
	<%= user.created_at %>
</td>
<td>
	Active
</td>
<td>  
  <%= user.role.titleize %>
</td>
<td>
  <%= link_to("Update user", edit_user_path(user), :method => :get, :class => 'button-xs') %>  
</td>
<td>
  <%= link_to("Enter User", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/_userhead.html.erb
<th> Account Name </th>
<th> Email </th>
<th> Member Since </th>
<th> User Status</th>
<th> User Type </th>
<th> Update User </th>
<th> Enter Account </th>

app/views/users/create.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/users/edit.html.erb
<div class="register-form">
  <%= form_for(@user) do |f| %>    
    <div class="form-header">
    <span>Add / Manage User</span>
    </div>
    <div class="form-body">      
      <div class="form-group">
        <%= f.label :name, 'Account Name' %>
        <%= f.text_field :name, :autofocus => true, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Account Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :contact, 'Contact' %>
        <%= f.text_field :contact, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :phone, 'Phone' %>
        <%= f.text_field :phone, class: 'form-control' %>
      </div>

      <div id='privilege_section'>
      <div class="form-group">
        <%= f.label :role,'User Type' %>
        <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
      </div>
      <label class="privilege-select">
      <%= f.check_box :caa%> 
        Create/Edit Admin Accounts
      </label>

      <label class="privilege-select">
      <%= f.check_box :cua%> 
        Create/Edit User Accounts
      </label>

      <label class="privilege-select">
      <%= f.check_box :pm%> 
        Publish Maps
      </label>

      <label class="privilege-select">
      <%= f.check_box :vsd%>
        View/Edit Source Data
      </label>
      <label class="privilege-select">
      <%= f.check_box :eci%>
        Export Chart Image
      </label>
      <label class="privilege-select">
        <%= f.check_box :etp%>
          Export to PDF
      </label>      
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
      <div class='form-group'>
        <%= link_to 'Enable Account', "/users", :class=>'btn outlined-btn', :id=>'enable_btn'%> 
        <%= link_to 'Disable Account', "/users", :class=>'btn outlined-btn', :id=>'disable_btn'%> 
      </div>
      <div class='form-group'>
        <%= link_to 'Cancel', "/users", :class=>'btn outlined-btn' %> 
        <%= f.submit 'Save', :class => 'button right', :id=>'save_btn'%>      
      </div>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<input type="hidden" class="page_type" value="manage_users"/>
<h3>Users</h3>     
<table id="manage_users_table" class="table responsive no-wrap">
  <thead>
    <%= render 'userhead' %>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <%= render user %>
      </tr>
    <% end %>
  </tbody>
</table>          

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>