config/routes.rb
Rails.application.routes.draw do
  get 'sidebar/index'

  root to: 'visitors#index'
  devise_for :users,controllers: {:registrations => "registrations"}
  resources :users
	as :user do
	  get "/register", to: "registrations#new", as: "register"
	  get "/maps/moremaps", to: "maps#moremaps"
	end
	resources :maps do
		collection {post:import}
		collection {post:ctg}
	end
	as :map do		
		get "maps/:id/vgs", to:"maps#vgs" , as: "groupsummary"		
		get "maps/:id/vcm", to:"maps#vcm" , as: "correlationmatrix"		
		get "maps/:id/vsg", to:"maps#viewsinglegraph" , as: "singlegraph"
		get "maps/:id/md", to:"maps#mapdashboard" , as: "mapdashboard"
	end	
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>  
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete'%></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav id="topnav" class="navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">        
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_settings.html.erb
<div id="settings-section">
	<h3>Maps</h3>     
	<p> Status: Published </p>
	<input type="text" id="graphColorPicker" value="black"/>
</div>

app/views/layouts/_sidebar.html.erb
<div class="nav-side-menu">
    <div class="brand">Rapid Talent Mapping</div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
    <div class="menu-list">
        <ul id="menu-content" class="menu-content collapse out">
            <li>
                <span class="item-title"> User Management </span>
            </li>
            <li>
                <a href="/users" class="menu-item">
                    Manage Users
                </a>
            </li>
            <li>
                <a href="/register" class="menu-item">
                    Add a User
                </a>
            </li>
            <hr class="item-divider">
            <li>
                <span class="item-title"> My Map </span>
            </li>                        

            <li class="input">
                <input id="search_map" type="text" placeholder="Find a Map" />
            </li>            
            
            <% unless $g_maps.nil? %>
              <% $g_maps.each_with_index do |map, index| %>
              <% if(index <5) %>
              <li>
                <%= link_to map.maptitle, map_path(map) ,:class => 'menu-item'%>
              </li>
              <% end %>
              <% end %>
            <% end %>

            <% if $g_maps.size > 5 %>
            <li>
                <%= s = $g_maps.size - 5
                link_to '...' + s.to_s + ' more maps', '/maps/moremaps' ,:class => 'menu-item'%>
            </li>
            <% end %>
            <li>                
                <%= link_to 'Create New Map', new_map_path ,:class => 'createMapBtn'%>
            </li>
            <hr class="item-divider">
            <li>
                <span class="item-title"> Map Details </span>                
            </li>            
            <% unless $selectedmap.nil? %>
            <%= render 'maps/detaillink' %>
            <% end %>
        </ul>
    </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "My Application" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "My Application" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">
  </head>
  <body>            
    <div id="wrapper">
      <!-- Navigation -->                  
      <%= render partial: "layouts/sidebar", locals: {map: $g_maps} %>
      <%= render 'layouts/navigation' %>
      <!-- Header -->
      <div id="main">
        <div class="container-fluid" >
            <div class="row">
                <div class="col-md-12">   
                  <div class="content">
                    <%= render 'layouts/messages' %>
                    <%= yield %>  
                  </div>
                </div>
            </div>
        </div>   
      </div>
      <a id="settingsBtn"><i class="fa fa-cog fa-2x" aria-hidden="true"></i></a>
      <%= render 'layouts/settings' %>
    </div>
  </body>
</html>